---
- name: Setup solr.service files
  ansible.builtin.template:
    src: solr.service.j2
    dest: /etc/systemd/system/solr.service
    owner: root
    group: root
    mode: '0644'

- name: Setup blacklight.server files
  ansible.builtin.template:
    src: blacklight.server.j2
    dest: /etc/systemd/system/blacklight.service
    owner: root
    group: root
    mode: '0644'  

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: yes

- name: Start solr
  ansible.builtin.systemd_service:
    name: solr
    state: started
    enabled: yes

- name: Start blacklight
  ansible.builtin.systemd_service:
    name: blacklight
    state: started
    enabled: yes

  