---
# - name: Check for System requirements
#   ansible.builtin.yum:
#     name:
#       - lsof
#   state: present
#   become: true
#   when: not ansible_check_mode

- name: Download Solr source tar
  ansible.builtin.get_url:
    url: https://www.apache.org/dyn/closer.lua/solr/solr/9.8.0/solr-9.8.0-src.tgz?action=download
    dest: /home
    mode: '0440'

- name: Run the installation script
  ansible.builtin.command: 'tar xzf solr-9.8.0.tgz solr-9.8.0/bin/install_solr_service.sh --strip-components=2 -n'


- name: Setup solr.service files
  ansible.builtin.template:
    src: solr.service.j2
    dest: /etc/systemd/system/solr.service
    owner: root
    group: root
    mode: '0644'

- name: Setup blacklight.server files
  ansible.builtin.template:
    src: blacklight.server.j2
    dest: /etc/systemd/system/blacklight.service
    owner: root
    group: root
    mode: '0644'  

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: yes

- name: Start solr
  ansible.builtin.systemd_service:
    name: solr
    state: started
    enabled: yes

- name: Start blacklight
  ansible.builtin.systemd_service:
    name: blacklight
    state: started
    enabled: yes

  